### ISSUE TITLE
低版本idea和java不支持

### ISSUE THREAD

**Issue by bqingAll** [zcbbpo/testable-idea#2]

**Comment by goldbrown** [comment]
我fork了一下，创建了[testable-idea](https://github.com/goldbrown/testable-idea)，将源代码改了一下，适配了2019版本的IDEA，应该可以支持2019.2版本的IDEA和java8。你试试，我的2019.2是可以用的，不知道2020和2021是否可以使用。直接使用  
testable-idea-1.3.5.beta.zip 这个压缩包就可以了

**Comment by zcbbpo** [comment]
@goldbrown 你可以提个pr吗？非常感谢

**Comment by goldbrown** [comment]
@zcbbpo 要不要新建一个分支。我的修改大致如下：
1）降低了gradle-idea插件的版本；
2）idea高版本没有的类，我手动复制出来了。
改的比较挫，我先提吧，你看看

**Comment by bqingAll** [comment]
2020.2版本可以安装插件了，谢谢
